import React from "react";

export function EWayBillTemplate({ invoice, printSet, gstSet, activeColor, numberToWords }) {
  const { customer, lines, totals, meta, paymentDetails } = invoice;
  const formatAmt = (val) => {
    const num = Number(val) || 0;
    return printSet.amountWithDecimal ? num.toFixed(2) : Math.round(num).toString();
  };

  const getInvoiceSizeClass = (size, fallback) => {
    if (!size || size === "Medium") return fallback;
    if (size === "Small") return "text-[8px]";
    if (size === "Large") return "text-[12px]";
    if (size === "Extra Large") return "text-[14px]";
    return fallback;
  };

  const baseTextClass = getInvoiceSizeClass(printSet.invoiceSize, "text-[10px]");

  const themeStyle = {
    color: activeColor?.raw || "#1e293b",
  };

  const themeBgStyle = {
    backgroundColor: activeColor?.raw || "#1e293b",
    color: "#fff",
  };

  return (
    <div className={`w-full bg-white p-6 font-sans ${baseTextClass} text-slate-800`}>
      <div className="border border-slate-200">
        
        {/* Header */}
        <div className="flex border-b border-slate-200">
          <div className="w-8 border-r border-slate-200 flex items-center justify-center">
            {/* Empty column in original */}
          </div>
          <div className="flex-1 p-2 flex justify-between items-center">
            <h1 className="font-bold text-lg" style={themeStyle}>e-Way Bill</h1>
            <div className="font-bold text-sm text-center">&lt;QR Code&gt;</div>
          </div>
        </div>

        {/* 1. E-WAY BILL Details */}
        <div className="p-2 border-b border-slate-200 font-bold" style={themeBgStyle}>
          1. E-WAY BILL Details
        </div>
        <div className="flex flex-wrap border-b border-slate-200 text-[9px]">
          <div className="w-1/3 p-2 border-r border-slate-200">
            <div>eWay Bill No: <span className="font-bold">{meta?.invoiceNumber || "-"}</span></div>
            <div className="mt-2">Mode: Road</div>
            <div className="mt-2">Type: Outward-Supply</div>
          </div>
          <div className="w-1/3 p-2 border-r border-slate-200">
            <div>Generated Date: {meta?.date || "-"}</div>
            <div className="mt-2">Approx Distance: 4km</div>
            <div className="mt-2">Document Details: {meta?.invoiceNumber || "-"}</div>
          </div>
          <div className="w-1/3 p-2">
            <div>Generated By: {gstSet?.gstin || "-"}</div>
            <div className="mt-2">Valid Upto: -</div>
            <div className="mt-2">Transaction type: Regular</div>
          </div>
        </div>

        {/* 2. Address Details */}
        <div className="p-2 border-b border-slate-200 font-bold" style={themeBgStyle}>
          2. Address Details
        </div>
        <div className="flex border-b border-slate-200 text-[9px]">
          <div className="w-1/2 p-2 border-r border-slate-200">
            <div className="font-bold mb-1">From</div>
            <div>GSTIN: {gstSet?.gstin || "-"}</div>
            <div className="font-bold uppercase mt-1">{printSet?.companyName || "Company Name"}</div>
            <div>{printSet?.state || meta?.placeOfSupply || "State"}</div>
            <div className="mt-2 text-slate-500">::Dispatch From::</div>
            <div>{printSet?.address}</div>
          </div>
          <div className="w-1/2 p-2">
            <div className="font-bold mb-1">To</div>
            <div>GSTIN: {meta?.billedToGstin || "-"}</div>
            <div className="font-bold uppercase mt-1">{customer || "Customer Name"}</div>
            <div>{meta?.billedToState || meta?.placeOfSupply || "State"}</div>
            <div className="mt-2 text-slate-500">::Ship To::</div>
            <div>{meta?.billedToAddress}</div>
          </div>
        </div>

        {/* 3. Goods Details */}
        <div className="p-2 border-b border-slate-200 font-bold" style={themeBgStyle}>
          3. Goods Details
        </div>
        <table className="w-full text-[9px] text-left border-b border-slate-200">
          <thead>
            <tr className="border-b border-slate-200 bg-slate-50">
              <th className="p-2 border-r border-slate-200 text-center font-bold">HSN Code</th>
              <th className="p-2 border-r border-slate-200 font-bold">Product Name & Desc</th>
              <th className="p-2 border-r border-slate-200 text-center font-bold">Quantity</th>
              <th className="p-2 border-r border-slate-200 text-right font-bold">Price</th>
              <th className="p-2 border-r border-slate-200 text-right font-bold">Discount</th>
              <th className="p-2 border-r border-slate-200 text-right font-bold">Taxable Amt</th>
              <th className="p-2 border-r border-slate-200 text-center font-bold">CGST+SGST</th>
              <th className="p-2 text-right font-bold">Total Amount</th>
            </tr>
          </thead>
          <tbody>
            {lines.map((l, idx) => {
              const q = Number(l.qty) || 0;
              const r = Number(l.rate || l.price) || 0;
              const d = Number(l.discount) || 0;
              const g = Number(l.gst) || 0;
              const rateAfterDisc = r * (1 - d / 100);
              const taxable = q * rateAfterDisc;
              const taxAmt = taxable * (g / 100);
              const lineTotal = taxable + taxAmt;

              return (
                <tr key={idx} className="border-b border-slate-100 last:border-none">
                  <td className="p-2 border-r border-slate-200 text-center">{l.hsnCode || "-"}</td>
                  <td className="p-2 border-r border-slate-200 font-semibold">{l.name || l.item || "-"}</td>
                  <td className="p-2 border-r border-slate-200 text-center">{q}</td>
                  <td className="p-2 border-r border-slate-200 text-right">{r.toFixed(2)}</td>
                  <td className="p-2 border-r border-slate-200 text-right">{d}%</td>
                  <td className="p-2 border-r border-slate-200 text-right">{taxable.toFixed(2)}</td>
                  <td className="p-2 border-r border-slate-200 text-center">{g}%</td>
                  <td className="p-2 text-right font-bold">{lineTotal.toFixed(2)}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
        
        {/* Additional Invoice Details Not in Original E-Way Bill */}
        <div className="flex">
          <div className="w-2/3 p-4 border-r border-slate-200 flex flex-col justify-between">
            {/* Bank Details */}
            {printSet.bankDetails && (
              <div className="mb-4 p-3 rounded bg-slate-50 border border-slate-200">
                <div className="text-[8px] font-bold text-slate-400 uppercase tracking-wider mb-2">Bank Account Details</div>
                <div className="grid grid-cols-3 gap-2">
                  <div className="text-slate-500">Account No.</div>
                  <div className="col-span-2 font-mono font-medium">{printSet.accountNumber || "-"}</div>
                  <div className="text-slate-500">Bank Name</div>
                  <div className="col-span-2 font-medium">{printSet.bankName || "-"}</div>
                  <div className="text-slate-500">IFSC Code</div>
                  <div className="col-span-2 font-mono font-medium">{printSet.ifscCode || "-"}</div>
                </div>
              </div>
            )}

            {/* Notes & Terms */}
            <div className="space-y-4">
              {printSet.notes && (
                <div>
                  <div className="font-bold text-[8px] uppercase text-slate-400 mb-1">Description / Notes</div>
                  <div className="text-slate-600 leading-relaxed whitespace-pre-wrap">{printSet.notes}</div>
                </div>
              )}
              {printSet.terms && (
                <div>
                  <div className="font-bold text-[8px] uppercase text-slate-400 mb-1">Terms & Conditions</div>
                  <div className="text-slate-600 leading-relaxed whitespace-pre-wrap">{printSet.terms}</div>
                </div>
              )}
            </div>
            
            {/* Amount in Words */}
            <div className="mt-4 border-t border-dashed border-slate-300 pt-2">
              <div className="text-[8px] font-bold text-slate-400 uppercase mb-1">Total Invoice Amount In Words</div>
              <div className="font-medium italic text-slate-700 capitalize">{numberToWords ? numberToWords(totals.grand) : "-"} Rupees Only</div>
            </div>
          </div>
          
          {/* Summary Details */}
          <div className="w-1/3 flex flex-col">
            <div className="flex-1 p-4 bg-slate-50">
              <div className="space-y-2">
                <div className="flex justify-between text-slate-600">
                  <span>Subtotal Before Tax</span>
                  <span>{formatAmt(totals.taxableAmount)}</span>
                </div>
                <div className="flex justify-between text-slate-600">
                  <span>Total GST Tax</span>
                  <span>{formatAmt(totals.gstAmount)}</span>
                </div>
                {totals.roundOff !== 0 && (
                  <div className="flex justify-between text-slate-600">
                    <span>Round Off</span>
                    <span>{totals.roundOff > 0 ? `+${totals.roundOff.toFixed(2)}` : totals.roundOff.toFixed(2)}</span>
                  </div>
                )}
                <div className="flex justify-between font-bold text-base pt-2 border-t border-slate-300" style={themeStyle}>
                  <span>AMOUNT WITH TAX</span>
                  <span>{formatAmt(totals.grand)}</span>
                </div>
                {paymentDetails?.received > 0 && (
                  <>
                    <div className="flex justify-between text-slate-500 pt-2">
                      <span>Received Amount</span>
                      <span>{formatAmt(paymentDetails.received)}</span>
                    </div>
                    <div className="flex justify-between font-medium pt-1">
                      <span>Balance Amount</span>
                      <span>{formatAmt(totals.grand - paymentDetails.received)}</span>
                    </div>
                  </>
                )}
              </div>
            </div>
            <div className="p-4 border-t border-slate-200 text-center">
              <div className="h-12 border-b border-dashed border-slate-300 mb-2"></div>
              <div className="text-[8px] text-slate-400 uppercase tracking-widest font-bold">Authorized Signatory</div>
              <div className="text-xs font-bold mt-1 text-slate-700">{printSet.companyName}</div>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
}
