import React from "react";
import Barcode from "react-barcode";

export function GreenEWay({ invoice, printSet, gstSet, numberToWords }) {
  const { customer, lines, totals, meta, transportDetails = {}, shippingDetails = {} } = invoice;
  
  const getInvoiceSizeClass = (size, fallback) => {
    if (!size || size === "Medium") return fallback;
    if (size === "Small") return "text-[8px]";
    if (size === "Large") return "text-[11px]";
    if (size === "Extra Large") return "text-[12px]";
    return fallback;
  };

  const baseTextClass = getInvoiceSizeClass(printSet.invoiceSize, "text-[9px]");

  const themeBgStyle = { backgroundColor: "#10b981", color: "#fff" }; // emerald-500
  const headerText = { color: "#10b981" };

  return (
    <div className={`w-full bg-white p-6 font-sans ${baseTextClass} text-slate-800 border-4 border-black box-border`}>
      <div className="border border-black">
        
        {/* Header Section */}
        <div className="flex border-b border-black">
          <div className="w-1/2 p-4 flex flex-col justify-center">
            <h1 className="font-bold text-3xl mb-1" style={headerText}>E-Way Bill</h1>
          </div>
          <div className="w-1/4 flex flex-col justify-center items-center p-2 border-l border-black">
            {printSet.logoUrl ? (
              <img src={printSet.logoUrl} alt="Logo" className="h-12 object-contain" />
            ) : (
              <div className="h-10 w-10 bg-slate-100 rounded-full flex items-center justify-center border text-xs">
                Logo
              </div>
            )}
            {printSet.companyName && (
              <span className="font-bold mt-1 text-[10px] text-red-600">{printSet.companyName}</span>
            )}
          </div>
          <div className="w-1/4 flex flex-col justify-center items-center p-2 border-l border-black text-center">
            <span className="font-bold text-[10px] mb-1">Add Your Qr Here</span>
            <div className="w-16 h-16 border border-black flex items-center justify-center bg-slate-50">
              <span className="text-[8px]">QR</span>
            </div>
          </div>
        </div>

        {/* 1. E-WAY BILL Details */}
        <div className="p-1 border-b border-black font-bold uppercase" style={themeBgStyle}>
          1. E-WAY BILL Details
        </div>
        <div className="flex flex-wrap border-b border-black">
          <div className="w-1/3 p-1.5 border-r border-black">
            <div>eWay Bill No: <span className="font-bold">{transportDetails.ewbNumber || meta?.invoiceNumber || "-"}</span></div>
            <div className="mt-2">Mode: {transportDetails.modeOfTransport || "Road"}</div>
            <div className="mt-2">Type: Outward-Supply</div>
          </div>
          <div className="w-1/3 p-1.5 border-r border-black">
            <div>Generated Date: {meta?.date || "-"}</div>
            <div className="mt-2">Approx Distance: {transportDetails.approxDistance || "-"}km</div>
            <div className="mt-2 flex">
              <span className="mr-1">Document Details:</span>
              <span className="break-all">Tax-Invoice-{meta?.invoiceNumber}-{meta?.date}</span>
            </div>
          </div>
          <div className="w-1/3 p-1.5">
            <div>Generated By: {gstSet?.gstin || "-"}</div>
            <div className="mt-2">Valid Upto: -</div>
            <div className="mt-2">Transaction type: Regular</div>
          </div>
        </div>

        {/* 2. Address Details */}
        <div className="p-1 border-b border-black font-bold uppercase" style={themeBgStyle}>
          2. Address Details
        </div>
        <div className="flex border-b border-black">
          <div className="w-1/2 border-r border-black">
            <div className="p-1 border-b border-black font-bold" style={themeBgStyle}>From</div>
            <div className="p-1.5">
              <div>GSTIN: {gstSet?.gstin || "-"}</div>
              <div className="mt-1">{printSet?.companyName || "Company Name"}</div>
              <div>{printSet?.state || meta?.placeOfSupply || "State"}</div>
              <div className="mt-3 text-slate-600">::Dispatch From::</div>
              <div className="whitespace-pre-wrap">{shippingDetails.dispatchFromAddress || printSet?.address || "-"}</div>
              {shippingDetails.placeOfDispatch && <div>{shippingDetails.placeOfDispatch}</div>}
            </div>
          </div>
          <div className="w-1/2">
            <div className="p-1 border-b border-black font-bold" style={themeBgStyle}>To</div>
            <div className="p-1.5">
              <div>GSTIN: {meta?.billedToGstin || "-"}</div>
              <div className="mt-1">{meta?.billingName || customer || "Customer Name"}</div>
              <div>{meta?.billedToState || meta?.placeOfSupply || "State"}</div>
              <div className="mt-3 text-slate-600">::Ship To::</div>
              <div className="whitespace-pre-wrap">{shippingDetails.shipToAddress || meta?.billedToAddress || "-"}</div>
              {shippingDetails.placeOfDelivery && <div>{shippingDetails.placeOfDelivery}</div>}
            </div>
          </div>
        </div>

        {/* 3. Goods Details */}
        <div className="p-1 border-b border-black font-bold uppercase" style={themeBgStyle}>
          3. Goods Details
        </div>
        <table className="w-full text-left border-b border-black">
          <thead>
            <tr className="border-b border-black bg-[#dcfce7]">
              <th className="p-1.5 border-r border-black font-bold text-center w-16">HSN Code</th>
              <th className="p-1.5 border-r border-black font-bold">Product Name & Desc</th>
              <th className="p-1.5 border-r border-black font-bold text-center w-16">Quantity</th>
              <th className="p-1.5 border-r border-black font-bold text-center w-20">Taxable Amount Rs.</th>
              <th className="p-1.5 font-bold text-center">Tax Rate (C+S+I+Cess+Cess Non.Advol)</th>
            </tr>
          </thead>
          <tbody>
            {lines.map((l, idx) => {
              const q = Number(l.qty) || 0;
              const r = Number(l.rate || l.price) || 0;
              const d = Number(l.discount) || 0;
              const g = Number(l.gst) || 0;
              const rateAfterDisc = r * (1 - d / 100);
              const taxable = q * rateAfterDisc;
              
              const sellerStateStr = printSet?.state || "";
              const customerStateStr = meta?.billedToState || "";
              const isInterstate = sellerStateStr && customerStateStr &&
                !(sellerStateStr.toLowerCase().replace(/[^a-z]/g, '') === customerStateStr.toLowerCase().replace(/[^a-z]/g, ''));

              const cgst = isInterstate ? 0 : g / 2;
              const sgst = isInterstate ? 0 : g / 2;
              const igst = isInterstate ? g : 0;
              const cess = Number(l.cess) || 0;

              const cgstStr = cgst > 0 ? `${cgst}%` : "0";
              const sgstStr = sgst > 0 ? `${sgst}%` : "0";
              const igstStr = igst > 0 ? `${igst}%` : "0";
              const cessStr = cess > 0 ? `${cess}%` : "0";

              return (
                <tr key={idx} className="border-b border-black border-dashed last:border-solid">
                  <td className="p-1 border-r border-black text-center">{l.hsnSac || l.hsnCode || "-"}</td>
                  <td className="p-1 border-r border-black">{l.name || l.item || "-"}</td>
                  <td className="p-1 border-r border-black text-center">{q}</td>
                  <td className="p-1 border-r border-black text-center">{taxable.toFixed(2)}</td>
                  <td className="p-1 text-center font-mono text-[9px] tracking-wide">
                    {cgstStr} + {sgstStr} + {igstStr} + {cessStr} + 0
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
        
        {/* Goods Summary */}
        <table className="w-full text-center border-b border-black bg-[#dcfce7]">
          <thead>
            <tr className="border-b border-black">
              <th className="p-1 border-r border-black font-bold leading-tight">Tot. Tax'ble Amt</th>
              <th className="p-1 border-r border-black font-bold">CGST Amt</th>
              <th className="p-1 border-r border-black font-bold">SGST Amt</th>
              <th className="p-1 border-r border-black font-bold">IGST Amt</th>
              <th className="p-1 border-r border-black font-bold">Cess Amt</th>
              <th className="p-1 border-r border-black font-bold leading-tight">Cess Non.Advol Amt</th>
              <th className="p-1 border-r border-black font-bold">Other Amt</th>
              <th className="p-1 font-bold">Tot. Inv. Amt</th>
            </tr>
          </thead>
          <tbody className="bg-white">
            {(() => {
              const sellerStateStr = printSet?.state || "";
              const customerStateStr = meta?.billedToState || "";
              const isInterstate = sellerStateStr && customerStateStr &&
                !(sellerStateStr.toLowerCase().replace(/[^a-z]/g, '') === customerStateStr.toLowerCase().replace(/[^a-z]/g, ''));

              const formatSummaryAmt = (val) => {
                const num = Number(val) || 0;
                return num === 0 ? "-" : num.toFixed(2);
              };

              return (
                <tr>
                  <td className="p-1.5 border-r border-black">{totals.taxableAmount.toFixed(2)}</td>
                  <td className="p-1.5 border-r border-black">{formatSummaryAmt(isInterstate ? 0 : totals.gstAmount / 2)}</td>
                  <td className="p-1.5 border-r border-black">{formatSummaryAmt(isInterstate ? 0 : totals.gstAmount / 2)}</td>
                  <td className="p-1.5 border-r border-black">{formatSummaryAmt(isInterstate ? totals.gstAmount : 0)}</td>
                  <td className="p-1.5 border-r border-black">{formatSummaryAmt(0)}</td>
                  <td className="p-1.5 border-r border-black">{formatSummaryAmt(0)}</td>
                  <td className="p-1.5 border-r border-black">{formatSummaryAmt(totals.roundOff)}</td>
                  <td className="p-1.5 font-bold">{totals.grand.toFixed(2)}</td>
                </tr>
              );
            })()}
          </tbody>
        </table>

        {/* 4. Transportation Details */}
        <div className="p-1 border-b border-black font-bold uppercase" style={themeBgStyle}>
          4. Transportation Details
        </div>
        <div className="flex border-b border-black bg-slate-50">
          <div className="w-1/2 p-1.5 border-r border-black flex gap-1">
            <span className="font-semibold text-slate-700">Transport ID & Name:</span>
            <span>{transportDetails.transporterId || "-"} {transportDetails.transporterName}</span>
          </div>
          <div className="w-1/2 p-1.5 flex gap-1">
            <span className="font-semibold text-slate-700">Transport Doc. No. & Date:</span>
            <span>{transportDetails.lrNumber || "-"} {transportDetails.lrDate ? new Date(transportDetails.lrDate).toLocaleDateString() : ""}</span>
          </div>
        </div>

        {/* 5. Vehicle Details */}
        <div className="p-1 border-b border-black font-bold uppercase" style={themeBgStyle}>
          5. Vehicle Details
        </div>
        <table className="w-full text-center">
          <thead>
            <tr className="border-b border-black" style={themeBgStyle}>
              <th className="p-1 border-r border-black">Mode</th>
              <th className="p-1 border-r border-black">Vehicle / Transport Doc. No. & Date</th>
              <th className="p-1 border-r border-black">From</th>
              <th className="p-1 border-r border-black">Entered Date</th>
              <th className="p-1 border-r border-black">Entered By</th>
              <th className="p-1 border-r border-black leading-tight">CEWB No.<br/>(If any)</th>
              <th className="p-1 leading-tight">Multi Veh. Info<br/>(if any)</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td className="p-1.5 border-r border-black">{transportDetails.modeOfTransport || "Road"}</td>
              <td className="p-1.5 border-r border-black">{transportDetails.vehicleNumber || "-"}</td>
              <td className="p-1.5 border-r border-black">{shippingDetails.placeOfDispatch || "-"}</td>
              <td className="p-1.5 border-r border-black">{meta?.date || "-"}</td>
              <td className="p-1.5 border-r border-black">{gstSet?.gstin || "-"}</td>
              <td className="p-1.5 border-r border-black">-</td>
              <td className="p-1.5">-</td>
            </tr>
          </tbody>
        </table>

      </div>

      {/* Barcode Footer */}
      <div className="mt-4 flex justify-center items-center">
        {transportDetails.ewbNumber ? (
          <Barcode 
            value={transportDetails.ewbNumber}
            width={1.5}
            height={40}
            fontSize={12}
            displayValue={true}
          />
        ) : (
          <div className="h-12 w-64 border flex flex-col items-center justify-center bg-slate-50">
            <div className="w-56 h-8 flex gap-[2px]">
              {Array.from({ length: 40 }).map((_, i) => (
                <div key={i} className={`h-full bg-black ${i%2===0 ? 'w-1' : (i%3===0 ? 'w-0.5' : 'w-[1px]')}`} />
              ))}
            </div>
            <span className="text-[8px] mt-1">No : 123456789000</span>
          </div>
        )}
      </div>
    </div>
  );
}
