import React from "react";
import Barcode from "react-barcode";

export function MinimalEWay({ invoice, printSet, gstSet, numberToWords }) {
  const { customer, lines, totals, meta, transportDetails = {}, shippingDetails = {} } = invoice;
  
  const getInvoiceSizeClass = (size, fallback) => {
    if (!size || size === "Medium") return fallback;
    if (size === "Small") return "text-[8px]";
    if (size === "Large") return "text-[11px]";
    if (size === "Extra Large") return "text-[12px]";
    return fallback;
  };

  const baseTextClass = getInvoiceSizeClass(printSet.invoiceSize, "text-[9px]");

  return (
    <div className={`w-full bg-white p-6 font-sans ${baseTextClass} text-slate-800 box-border`}>
        
      {/* Header Section */}
      <div className="flex justify-between items-start mb-6">
        <h1 className="font-bold text-2xl">e-Waybill</h1>
        <div className="flex flex-col items-end">
          <div className="w-16 h-16 border border-slate-300 flex items-center justify-center mb-1">
            <span className="text-[8px] text-slate-400">QR Code</span>
          </div>
        </div>
      </div>

      {/* 1. E-WAY BILL Details */}
      <div className="font-bold mb-2 text-[11px]">E-Way Bill Details</div>
      <div className="border border-black mb-6">
        <div className="flex flex-wrap text-[9px]">
          <div className="w-1/3 p-2 border-r border-black">
            <div className="mb-2">eWay Bill No: <span className="font-bold">{transportDetails.ewbNumber || meta?.invoiceNumber || "1111 1111 1111"}</span></div>
            <div className="mb-2 border-t border-black pt-2">Mode: <span className="font-bold">{transportDetails.modeOfTransport || "Road"}</span></div>
            <div className="border-t border-black pt-2">Type: <span className="font-bold">Outward - Supply</span></div>
          </div>
          <div className="w-1/3 p-2 border-r border-black">
            <div className="mb-2">Generated Date: {meta?.date || "-"}</div>
            <div className="mb-2 border-t border-black pt-2">Approx Distance: {transportDetails.approxDistance || "-"}kms</div>
            <div className="border-t border-black pt-2">Document Details: Tax Invoice - {meta?.invoiceNumber} - {meta?.date}</div>
          </div>
          <div className="w-1/3 p-2">
            <div className="mb-2">Generated By: {gstSet?.gstin || "-"}</div>
            <div className="mb-2 border-t border-black pt-2">Valid Upto: -</div>
            <div className="border-t border-black pt-2">Transaction type: Regular</div>
          </div>
        </div>
      </div>

      {/* 2. Address Details */}
      <div className="font-bold mb-2 text-[11px]">Address Details</div>
      <div className="border border-black mb-6 flex">
        <div className="w-1/2 p-2 border-r border-black">
          <div className="font-bold mb-2">From</div>
          <div>GSTIN: {gstSet?.gstin || "-"}</div>
          <div className="mt-1">{printSet?.companyName || "Company Name"}</div>
          <div>{printSet?.state || meta?.placeOfSupply || "State"}</div>
          <div className="mt-3 text-slate-600">:: Dispatch From ::</div>
          <div className="whitespace-pre-wrap">{shippingDetails.dispatchFromAddress || printSet?.address || "-"}</div>
          {shippingDetails.placeOfDispatch && <div>{shippingDetails.placeOfDispatch}</div>}
        </div>
        <div className="w-1/2 p-2">
          <div className="font-bold mb-2">To</div>
          <div>GSTIN: {meta?.billedToGstin || "-"}</div>
          <div className="mt-1">{meta?.billingName || customer || "Customer Name"}</div>
          <div>{meta?.billedToState || meta?.placeOfSupply || "State"}</div>
          <div className="mt-3 text-slate-600">:: Ship To ::</div>
          <div className="whitespace-pre-wrap">{shippingDetails.shipToAddress || meta?.billedToAddress || "-"}</div>
          {shippingDetails.placeOfDelivery && <div>{shippingDetails.placeOfDelivery}</div>}
        </div>
      </div>

      {/* 3. Goods Details */}
      <div className="font-bold mb-2 text-[11px]">Goods Details</div>
      <table className="w-full text-left border border-black mb-2">
        <thead>
          <tr className="border-b border-black">
            <th className="p-2 border-r border-black font-bold">HSN Code</th>
            <th className="p-2 border-r border-black font-bold">Product Name & Desc.</th>
            <th className="p-2 border-r border-black font-bold">Quantity</th>
            <th className="p-2 border-r border-black font-bold">Taxable Amount Rs.</th>
            <th className="p-2 font-bold">Tax Rate (C + S + I + Cess + Cess Non. Advol)</th>
          </tr>
        </thead>
        <tbody>
          {lines.map((l, idx) => {
            const q = Number(l.qty) || 0;
            const r = Number(l.rate || l.price) || 0;
            const d = Number(l.discount) || 0;
            const g = Number(l.gst) || 0;
            const rateAfterDisc = r * (1 - d / 100);
            const taxable = q * rateAfterDisc;
            
            const cgst = g / 2;
            const sgst = g / 2;

            return (
              <tr key={idx} className="border-b border-black last:border-none">
                <td className="p-2 border-r border-black">{l.hsnSac || l.hsnCode || "-"}</td>
                <td className="p-2 border-r border-black">{l.name || l.item || "-"}</td>
                <td className="p-2 border-r border-black">{q} {l.unit || "NOS"}</td>
                <td className="p-2 border-r border-black">{taxable.toFixed(2)}</td>
                <td className="p-2">{cgst.toFixed(1)} + {sgst.toFixed(1)} + 0.0 + 0.0 + 0.0</td>
              </tr>
            );
          })}
        </tbody>
      </table>
      
      {/* Goods Summary */}
      <table className="w-full text-left border border-black mb-6">
        <thead>
          <tr className="border-b border-black">
            <th className="p-2 border-r border-black font-bold">Tot. Taxable Amt.</th>
            <th className="p-2 border-r border-black font-bold">CGST Amt.</th>
            <th className="p-2 border-r border-black font-bold">SGST Amt.</th>
            <th className="p-2 border-r border-black font-bold">IGST Amt.</th>
            <th className="p-2 border-r border-black font-bold">CESS Amt.</th>
            <th className="p-2 border-r border-black font-bold">CESS Non. Advol Amt.</th>
            <th className="p-2 border-r border-black font-bold">Other Amt.</th>
            <th className="p-2 font-bold">Total Inv. Amt.</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td className="p-2 border-r border-black">
              <div className="border border-black p-1">{totals.taxableAmount.toFixed(2)}</div>
            </td>
            <td className="p-2 border-r border-black">
              <div className="border border-black p-1">{(totals.gstAmount / 2).toFixed(2)}</div>
            </td>
            <td className="p-2 border-r border-black">
              <div className="border border-black p-1">{(totals.gstAmount / 2).toFixed(2)}</div>
            </td>
            <td className="p-2 border-r border-black">
              <div className="border border-black p-1">0.0</div>
            </td>
            <td className="p-2 border-r border-black">
              <div className="border border-black p-1">0.0</div>
            </td>
            <td className="p-2 border-r border-black">
              <div className="border border-black p-1">0.0</div>
            </td>
            <td className="p-2 border-r border-black">
              <div className="border border-black p-1">{totals.roundOff.toFixed(2)}</div>
            </td>
            <td className="p-2">
              <div className="border border-black p-1">{totals.grand.toFixed(2)}</div>
            </td>
          </tr>
        </tbody>
      </table>

      {/* 4. Transportation Details */}
      <div className="font-bold mb-2 text-[11px]">Transportation Details</div>
      <div className="flex border border-black mb-6">
        <div className="w-1/2 p-2 border-r border-black flex gap-1">
          <span className="font-semibold">Transporter ID & Name:</span>
          <span>{transportDetails.transporterId || "-"} {transportDetails.transporterName || ""}</span>
        </div>
        <div className="w-1/2 p-2 flex gap-1">
          <span className="font-semibold">Transporter Doc. No & Date:</span>
          <span>{transportDetails.lrNumber || "None"} & {transportDetails.lrDate ? new Date(transportDetails.lrDate).toLocaleDateString() : "None"}</span>
        </div>
      </div>

      {/* 5. Vehicle Details */}
      <div className="font-bold mb-2 text-[11px]">Vehicle Details</div>
      <table className="w-full text-left border border-black mb-8">
        <thead>
          <tr className="border-b border-black">
            <th className="p-2 border-r border-black font-bold">Mode</th>
            <th className="p-2 border-r border-black font-bold">Vehicle / Trans Doc. No. & Dt.</th>
            <th className="p-2 border-r border-black font-bold">From</th>
            <th className="p-2 border-r border-black font-bold">Entered Date</th>
            <th className="p-2 border-r border-black font-bold">Entered By</th>
            <th className="p-2 border-r border-black font-bold">CEWB No. (if any)</th>
            <th className="p-2 font-bold">Multi Veh. Info (if any)</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td className="p-2 border-r border-black">{transportDetails.modeOfTransport || "Road"}</td>
            <td className="p-2 border-r border-black">{transportDetails.vehicleNumber || "-"}</td>
            <td className="p-2 border-r border-black">{shippingDetails.placeOfDispatch || "-"}</td>
            <td className="p-2 border-r border-black">{meta?.date || "-"}</td>
            <td className="p-2 border-r border-black">{gstSet?.gstin || "-"}</td>
            <td className="p-2 border-r border-black">-</td>
            <td className="p-2">-</td>
          </tr>
        </tbody>
      </table>

      {/* Barcode Footer */}
      <div className="mt-4 flex justify-center items-center pb-8 border-b border-slate-300">
        {transportDetails.ewbNumber ? (
          <Barcode 
            value={transportDetails.ewbNumber}
            width={1.5}
            height={40}
            fontSize={12}
            displayValue={true}
          />
        ) : (
          <div className="h-12 w-64 border flex flex-col items-center justify-center bg-slate-50">
            <div className="w-56 h-8 flex gap-[2px]">
              {Array.from({ length: 40 }).map((_, i) => (
                <div key={i} className={`h-full bg-black ${i%2===0 ? 'w-1' : (i%3===0 ? 'w-0.5' : 'w-[1px]')}`} />
              ))}
            </div>
            <span className="text-[8px] mt-1">111111111111</span>
          </div>
        )}
      </div>
    </div>
  );
}
