import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const fmt = (n) =>
  "Rs. " + n.toLocaleString("en-IN", { maximumFractionDigits: 2 });

export function downloadInvoicePdf(data) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();

  // Header band
  doc.setFillColor(76, 175, 80);
  doc.rect(0, 0, pageW, 70, "F");
  doc.setTextColor(255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text(data.business.name, 40, 32);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(data.business.address, 40, 48);
  doc.text(`GSTIN: ${data.business.gstin}  |  ${data.business.phone}`, 40, 62);

  doc.setTextColor(255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("TAX INVOICE", pageW - 40, 32, { align: "right" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`#${data.number}`, pageW - 40, 48, { align: "right" });
  doc.text(data.date, pageW - 40, 62, { align: "right" });

  // Bill To
  doc.setTextColor(30, 41, 59);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Bill To", 40, 100);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(data.party.name, 40, 116);
  if (data.party.phone) doc.text(data.party.phone, 40, 130);
  if (data.party.address) doc.text(data.party.address, 40, 144);

  // Items table
  const rows = data.lines.map((l, i) => {
    const sub = l.qty * l.rate;
    const tax = (sub * l.gst) / 100;
    return [
      String(i + 1),
      l.name,
      String(l.qty),
      fmt(l.rate),
      `${l.gst}%`,
      fmt(tax),
      fmt(sub + tax),
    ];
  });

  const subtotal = data.lines.reduce((s, l) => s + l.qty * l.rate, 0);
  const totalTax = data.lines.reduce(
    (s, l) => s + (l.qty * l.rate * l.gst) / 100,
    0,
  );
  const grand = subtotal + totalTax;

  autoTable(doc, {
    startY: 170,
    head: [["#", "Item", "Qty", "Rate", "GST", "Tax", "Amount"]],
    body: rows,
    headStyles: { fillColor: [241, 245, 249], textColor: [30, 41, 59], fontStyle: "bold" },
    styles: { fontSize: 10, cellPadding: 6 },
    columnStyles: {
      0: { cellWidth: 28 },
      2: { halign: "right" },
      3: { halign: "right" },
      4: { halign: "right" },
      5: { halign: "right" },
      6: { halign: "right" },
    },
  });

  const endY = doc.lastAutoTable.finalY + 20;

  doc.setFontSize(10);
  doc.text("Subtotal", pageW - 180, endY);
  doc.text(fmt(subtotal), pageW - 40, endY, { align: "right" });
  doc.text("Total GST", pageW - 180, endY + 16);
  doc.text(fmt(totalTax), pageW - 40, endY + 16, { align: "right" });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Grand Total", pageW - 180, endY + 38);
  doc.text(fmt(grand), pageW - 40, endY + 38, { align: "right" });

  if (data.notes) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(100);
    doc.text(`Notes: ${data.notes}`, 40, endY + 70);
  }

  doc.setFontSize(8);
  doc.setTextColor(120);
  doc.text(
    "This is a computer-generated invoice. Generated by Udaan.",
    pageW / 2,
    doc.internal.pageSize.getHeight() - 24,
    { align: "center" },
  );

  doc.save(`${data.number}.pdf`);
}
